name: .NET Core API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  

    env:
      Solution_Name: SoderiaLaNueva-Api.sln                         

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Instalar el SDK de .NET Core (en este caso .NET 9)
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Restaurar las dependencias del proyecto
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}

    # Compilar la API
    - name: Build API
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}
      env:
        Configuration: ${{ matrix.configuration }}

    # Ejecutar las pruebas unitarias
    - name: Run tests
      run: dotnet test $env:Solution_Name --configuration ${{ matrix.configuration }}
      env:
        Configuration: ${{ matrix.configuration }}
